### ISSUE TITLE
Add Integration for Veeva CLM Surveys

### ISSUE THREAD

**Issue by plamont** [codeworksdev/mochi#254]
Incorporate the functionality as outlined in this survey-code example.   
The 2 main js files to look at are:

- veeva-library-addendum_survey_iDC.js: contains all of the necessary hooks into retrieving and submitting survey question and answers.

- slide.js: contains custom code which will get all survey questions assigned to a multichannel presentation create specific input types (text, select, multiselect, checkbox, radio etc.) and submit or update the responses automatically.

[survey-code.zip](https://github.com/codeworksdev/mochi/files/2895669/survey-code.zip)

**Comment by omkarrojekar** [comment]
Hi, I need some help that we have designed the survey in HTML. but we are confused about how to send a response and save it in veeva survey
